### ISSUE TITLE
error when opening ideas

### ISSUE THREAD

**Issue by totox777** [ivandiazwm/phpback#10]
I login as admin and created ideas, and then I try to open it via click on its category, but this error appear:

```javascript
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

SELECT * FROM ideas WHERE categoryid='1' AND status !='new' ORDER BY votes DESC LIMIT 0,

Filename: /home/jarfeed/public_html/models/get.php

Line Number: 111
```

**Comment by ivandiazwm** [comment]
This is weird, I can't reproduce the issue. But this is caused by not having the limit value of LIMIT (it should be `DESC LIMIT 0, 10`)  or whatever the value of the `max_results` setting is (stored in [$max variable](https://github.com/ivandiazwm/phpback/blob/master/application/models/get.php#L90)).
It should have the [initial value of 10](https://github.com/ivandiazwm/phpback/blob/master/install/install2.php#L24).

I'd recommend you to go to the `Admin Panel` and then `System Settings`. In the tab `General Settings` you should find the `max_results` edit field. If you don't, there probably was a problem with the installation. You should run the `install/install2.php` script aging in this case to generate the default value settings.

**Comment by totox777** [comment]
I see, will try to reinstall then
