### ISSUE TITLE
PHPBack is dead?

### ISSUE THREAD

**Issue by wouldsmina** [ivandiazwm/phpback#148]
Hi @ivandiazwm,

there is no contribution since 1 year. is phpback dead?

**Comment by ivandiazwm** [comment]
Hi @wouldsmina . Currently, I'm not developing new features for PHPBack. However, I'm maintaining it by reviewing and merging PR and bug fixing if there are any.
I'll continue development of this software in the future since I'm currently working on another project. But I will take my time to review submitted PRs and make releases.

**Comment by wouldsmina** [comment]
thanks for these informations. All the best.
